
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 20 23:10:35 EDT 2007
//----------------------------------------------------

package org.gotpike.pdt.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 99;
  public static final int TOK_NOT = 14;
  public static final int TOK_COMMENT = 7;
  public static final int TOK_FLOAT = 4;
  public static final int GT = 100;
  public static final int TOK_SWITCH = 20;
  public static final int TOK_DEC = 8;
  public static final int TOK_ADD_EQ = 25;
  public static final int TOK_EXTERN = 40;
  public static final int TOK_DIV_EQ = 34;
  public static final int TOK_RETURN = 9;
  public static final int TOK_PUBLIC = 70;
  public static final int TOK_COLON_COLON = 31;
  public static final int TOK_OPTIONAL = 81;
  public static final int TOK_NO_MASK = 63;
  public static final int TOK_LOR = 18;
  public static final int TOK_ENUM = 39;
  public static final int TOK_CLASS = 30;
  public static final int TOK_NE = 13;
  public static final int TOK_DEFAULT = 33;
  public static final int RBRACK = 83;
  public static final int TOK_AND_EQ = 26;
  public static final int COMMA = 87;
  public static final int RBRACE = 89;
  public static final int RPAREN = 92;
  public static final int TOK_WHILE = 79;
  public static final int TOK_CONSTANT = 3;
  public static final int TOK_VOID_ID = 78;
  public static final int LBRACK = 82;
  public static final int LT = 101;
  public static final int TOK_MULT_EQ = 62;
  public static final int TOK_LEX_EOF = 24;
  public static final int LBRACE = 88;
  public static final int LPAREN = 91;
  public static final int TOK_CONTINUE = 32;
  public static final int TOK_INT_ID = 53;
  public static final int TOK_OBJECT_ID = 64;
  public static final int TOK_STRING_ID = 73;
  public static final int TOK_FOR = 42;
  public static final int TOK_GE = 11;
  public static final int TOK_BREAK = 28;
  public static final int TOK_IMPORT = 48;
  public static final int TOK_RSH = 16;
  public static final int TOK_IDENTIFIER = 46;
  public static final int TOK_FOREACH = 23;
  public static final int TOK_TYPEDEF = 75;
  public static final int COMP = 96;
  public static final int TOK_OR_EQ = 65;
  public static final int TOK_GLOBAL = 45;
  public static final int EQ = 90;
  public static final int MOD = 98;
  public static final int TOK_STRING = 5;
  public static final int TOK_MULTISET_END = 56;
  public static final int TOK_INC = 19;
  public static final int TOK_DOT_DOT_DOT = 37;
  public static final int TOK_PRIVATE = 66;
  public static final int TOK_STATIC = 72;
  public static final int TOK_SSCANF = 21;
  public static final int TOK_LE = 12;
  public static final int TOK_GAUGE = 44;
  public static final int PLUS = 94;
  public static final int QUESTION = 105;
  public static final int TOK_LSH = 15;
  public static final int TOK_FUNCTION_ID = 43;
  public static final int TOK_SUB_EQ = 74;
  public static final int TOK_TYPEOF = 76;
  public static final int TOK_ELSE = 38;
  public static final int TOK_EQ = 10;
  public static final int DIV = 97;
  public static final int MULT = 86;
  public static final int TOK_PREDEF = 69;
  public static final int TOK_PROGRAM_ID = 67;
  public static final int DOT = 84;
  public static final int TOK_VARIANT = 77;
  public static final int SEMICOLON = 85;
  public static final int EOF = 0;
  public static final int TOK_FLOAT_ID = 41;
  public static final int MINUS = 95;
  public static final int TOK_DO = 35;
  public static final int TOK_MULTISET_ID = 55;
  public static final int TOK_MULTISET_START = 57;
  public static final int TOK_LAMBDA = 54;
  public static final int OR = 104;
  public static final int TOK_ARROW = 2;
  public static final int TOK_MOD_EQ = 61;
  public static final int error = 1;
  public static final int TOK_MIXED_ID = 60;
  public static final int TOK_FINAL_ID = 52;
  public static final int COLON = 93;
  public static final int TOK_CASE = 29;
  public static final int TOK_XOR_EQ = 80;
  public static final int TOK_LOCAL_ID = 51;
  public static final int TOK_PROTECTED = 68;
  public static final int TOK_RSH_EQ = 71;
  public static final int TOK_LAND = 17;
  public static final int TOK_MAPPING_ID = 59;
  public static final int TOK_CATCH = 22;
  public static final int TOK_DOT_DOT = 36;
  public static final int TOK_ARRAY_ID = 27;
  public static final int TOK_NUMBER = 6;
  public static final int TOK_INLINE = 50;
  public static final int AND = 102;
  public static final int TOK_LSH_EQ = 58;
  public static final int TOK_IF = 47;
  public static final int XOR = 103;
  public static final int TOK_INHERIT = 49;
}

